version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coin_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-network

volumes:
  mysql_data:

networks:
  dev-network: